/*
 * PostConstants
 */

module.exports = {
	GET_USER_POSTS: 'GET_USER_POSTS',
	RECIEVE_CREATED_POST: 'RECIEVE_CREATED_POST',
	RECIEVE_USER_POSTS: 'RECIEVE_USER_POSTS',
	RECIEVE_NEW_VOTE: 'RECIEVE_NEW_VOTE',
	UPVOTE_POST: 'UPVOTE_POST',
	WRITE_POST: 'WRITE_POST',
	GET_POST_BATCH: 'GET_POST_BATCH',
	POST_CREATE: 'POST_CREATE',
	RECIEVE_RAW_POSTS: 'RECIEVE_RAW_POSTS',
	SORT_POSTS: 'SORT_POSTS',
	FILTER_POSTS_GENRE: 'FILTER_POSTS_GENRE',
};