/*
 * PostConstants
 */

module.exports = {
	GET_USER_POSTS: 'GET_USER_POSTS',
	RECIEVE_CREATED_POST: 'RECIEVE_CREATED_POST',
	RECIEVE_USER_POSTS: 'RECIEVE_USER_POSTS',
	RECIEVE_NEW_VOTE: 'RECIEVE_NEW_VOTE',
	UPVOTE_POST: 'UPVOTE_POST',
	UNVOTE_POST: 'UNVOTE_POST',
	WRITE_POST: 'WRITE_POST',
	GET_POST_BATCH: 'GET_POST_BATCH',
	POST_CREATE: 'POST_CREATE',
	RECIEVE_RAW_POSTS: 'RECIEVE_RAW_POSTS',
	SORT_POSTS: 'SORT_POSTS',
	FILTER_POSTS: 'FILTER_POSTS',
	SET_CURR_POST: 'SET_CURR_POST',
	GET_SINGLE_POST: 'GET_SINGLE_POST',
	RECIEVE_NEW_POST: 'RECIEVE_NEW_POST',
	RECIEVE_NEW_COMMENT: 'RECIEVE_NEW_COMMENT',
	ERROR_MESSAGE: 'ERROR_MESSAGE',
	GET_MORE_POSTS: 'GET_MORE_POSTS',
	GET_ADMIN_POSTS: 'GET_ADMIN_POSTS',
	DELETE_ADMIN_POST: 'DELETE_ADMIN_POST', 
	BATCH_UPVOTE_POST: 'BATCH_UPVOTE_POST'
};