/*
 * PostConstants
 */

module.exports = {
	GET_CURRENT_USER: 'GET_CURRENT_USER',
	RECIEVE_CREATED_POST: 'RECIEVE_CREATED_POST',
	WRITE_POST: 'WRITE_POST',
	GET_POST_BATCH: 'GET_POST_BATCH',
	POST_CREATE: 'POST_CREATE',
	POST_UPVOTE: 'POST_UPVOTE',
	RECIEVE_RAW_POSTS: 'RECIEVE_RAW_POSTS',
	SORT_POSTS: 'SORT_POSTS',
	FILTER_POSTS_GENRE: 'FILTER_POSTS_GENRE',
};