/*
 * PostConstants
 */

module.exports = {
	GET_CURRENT_USER: 'GET_CURRENT_USER',
	GET_USER_POSTS: 'GET_USER_POSTS',
	GET_USER: 'GET_USER',
	UPDATE_EMAIL: 'UPDATE_EMAIL',
	RECIEVE_USER_POSTS: 'RECIEVE_USER_POSTS',
	RECIEVE_CURR_USER: 'RECIEVE_CURR_USER',
	RECIEVE_USER: 'RECIEVE_USER', 
	SEND_USER_APP: 'SEND_USER_APP',
	RECIEVE_APP_CONFIRM: 'RECIEVE_APP_CONFIRM',
	FOLLOW_USER: 'FOLLOW_USER',
	UNFOLLOW_USER: 'UNFOLLOW_USER',
	UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
	GET_USER_NOTIFICATIONS: 'GET_USER_NOTIFICATIONS',
	RECIEVE_USER_NOTIFICATIONS: 'RECIEVE_USER_NOTIFICATIONS'
};