/*
 * PostConstants
 */

module.exports = {
	GET_CURRENT_USER: 'GET_CURRENT_USER',
	GET_USER_POSTS: 'GET_USER_POSTS',
	GET_USER: 'GET_USER',
	UPDATE_EMAIL: 'UPDATE_EMAIL',
	RECIEVE_USER_POSTS: 'RECIEVE_USER_POSTS',
	RECIEVE_CURR_USER: 'RECIEVE_CURR_USER',
	RECIEVE_USER: 'RECIEVE_USER'
};